# Generated by Django 3.2.6 on 2021-09-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booing_date',
            new_name='booking_date',
        ),
    ]
