# Generated by Django 3.2.6 on 2021-10-01 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_worker_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='image',
        ),
    ]
